#!/bin/sh
ARG="$1"

# empty - empty the contents of ~/.trash
#
# Copyright (C) 2011 Klaatu la Terible
#
# This program is free software; you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation; either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program; if not, write to the Free Software
# Foundation, Inc., 51 Franklin St, Fifth Floor, Boston, MA 02110-1301, USA.

# seems silly to have a conf file for trash
# so im pulling in BASKET var from trashy script
#BASKET=$(grep -m1 BASKET $(which trash) | cut -f2 -d"=")

case "$(uname | tr [:upper:] [:lower:] )" in
    linux) BASKET=~/.local/share/Trash/files/ ;;
    bsd) BASKET=~/.local/share/Trash/files/ ;;
    sun) BASKET=~/.local/share/Trash/files/ ;;
    darwin) BASKET=~/.Trash ;; #check when around a mac
    *) echo "cannot find your trash" && exit ;;
esac

if [ "X$ARG" == "X-v" ]
	then
    VERBOSE=v
else
    VERBOSE=""
fi

find $BASKET -delete -mindepth 1

echo "Your trash is now empty."
