.\" trashy - an rm intermediary
.TH "trashy" "8" ""  "Klaatu" ""
.SH "NAME"
trashy \- trash in the shell
.SH "SYNOPSIS"
\fBtrash\fP file1 file2...
.nf 
\fBempty\fP [option]
.SH "DESCRIPTION"
.PP 
There is an unhealthy habit that arises with many a POSIX user: the
careless and wreckless use of the dreaded \fBrm\fP command. The \fBtrashy\fP command set is
a helpful intermediary that intervenes when you would otherwise use
\fBrm\fP. It consists of two commands: \fBtrash\fP, which moves your
file or files to your system `trash can`, and \fBempty\fP, which
removes files from your system trash.
.SH "USAGE"
.TP
Issue this command:
.PP
\fBtrash\fP foo
.PP
and foo will be moved to the system trash.
.PP
At this point, you have not yet removed the file from your system, so
if you wish to recover it, go and fetch it from your trash. There, now
isn't that nicer than \fBrm\fP?
.PP
When you're really really sure that everything in
your Trash wants to be nuked out of existance, then you can
issue the command:
.PP
empty
.PP
and your Trash will be emptied.
.PP
If there are spaces in your filenames, first of all stop using spaces
in your filenames. Secondly, you must escape the space when you trash
it:
.PP
\fBtrash\fP foo\\ bar
.PP
If you issue \fBtrash\fP without any arguments, it tells you the
current size of your system trash.
.SH OPTIONS
.PP
.TP
.B -v, --verbose
Makes \fBtrash\fP and \fBempty\fP verbose.
.TP
.B -d, --dry-run, --dryrun
Does not actually move or remove files, just shows what will happen if
you really did. This works for both \fBtrash\fP and \fBempty\fP
.SH "SYSTEM TRASH LOCATIONS"
.TP
On Linux, BSD, Ilumos, and Solaris, the system trash, by default, is
that defined by the Free Desktop specification: ~/.local/share/Trash/files/
.PP
If you do not use an environment that plays nice with the Free Desktop
spec (such as Mac OS) then trashy will attempt to detecte and use
your actual system trash.
.PP
If you are not on any recognizable POSIX system then a ~/.trash
directory is created and used as a fallback.
.PP
.SH "BUGS AND ISSUES"
.TP
Things can get a little messy when you're trashing files from an
external drive, because \fBtrash\fP moves the file from your external
drive to your system harddrive. It works, but it's not as graceful as,
say, creating a .trash folder on that external drive and hiding stuff
there until later.
.SH "SEE ALSO"
.nf
.I rm (1)
.I mv (1)
.URL http://slackermedia.info/trashy
.URL http://trash-cli.wahtever
.fi
.PP
.SH "AUTHORS"
.nf
Klaatu (klaatu@member.fsf.org)
.fi
.PP
.SH "BUGS"
Email bugs reports or fixes to klaatu@member.fsf.org
.fi
