#!/bin/bash
ARG="$@"

CHECK=$(ls -a ~ | grep -i .trash)
if [ "X$CHECK" == "X" ]
	then mkdir ~/.trash
fi

if [ "X$ARG" == "X.trash" ]
	then 
	echo "You cannot trash the .trash"
	echo "Try issuing the command /bin/rm -rf ~/.trash instead."
	else
	if [ "X$ARG" != "X" ]
		then
		mv $ARG ~/.trash/
		RETURN=$(basename $ARG)
		echo "$RETURN moved to Trash.  Your Trash is currently $(du -h ~/.trash | cut -f1 | tail -n -1) in size."
		else
		echo "Your trash is currently $(du -h ~/.trash | cut -f1) in size."
	fi
fi
