#!/bin/bash
ARG="$@"

CHECK=$(ls -a ~ | grep -i .trash)
if [ ! -d " " ]
	then mkdir -m 700 ~/.trash 2> /dev/null
fi

if [ "X$ARG" == "X.trash" ]
	then 
	echo "You cannot trash the .trash"
	echo "Use the empty command to empty the trash."	
	echo "Or use /bin/rm -rf ~/.trash if you are trying to delete the .trash folder."
	else
	if [ "X$ARG" != "X" ]
		then
		mv -b "$ARG" ~/.trash/"$ARG"_$(date | cut -f 2-5 -d ' ' | tr ' ' '_' | tr ':' '.') || exit 1
		# useless user friendly reassuring fluffy stuff
		RETURN="$ARG"
		if [ "X$2" != "X" ]
			then echo "Multiple files have been moved to the trash."
			else
			echo "$RETURN has been moved to the trash."	
		fi

		echo "Your Trash is currently $(du -h ~/.trash | cut -f1 | tail -n -1) in size."
		else
		echo "Your trash is currently $(du -h ~/.trash | cut -f1) in size."
	fi
fi
